### ISSUE TITLE
Failed loading provided credentials. Make sure to provide a string or a file path. Reason: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by christianfurr** [Lakshya0257/LUNA#1]
```python
Failed loading provided credentials. Make sure to provide a string or a file path. Reason: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/christianfurr/Desktop/Code/LUNA/app.py", line 141, in <module>
    ytmusic = YTMusic('D:\Web dev\Luna\python\headers_auth.json')
  File "/Users/christianfurr/Library/Python/3.9/lib/python/site-packages/ytmusicapi/ytmusic.py", line 98, in __init__
    if 'x-goog-visitor-id' not in self.headers:
AttributeError: 'YTMusic' object has no attribute 'headers'
```

not too sure whats going I am on macos and I think thats what is making it mad bucase its calling to `D:\` which I dont think is on macOS , I also didnt put in a env but I dont think thats the issue

**Comment by Lakshya0257** [comment]
Step1: Create a headers_auth.json file in your root folder and copy the file path in the YtMusic Instance.
Step2: In your header json file copy and paste the below code
{
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
    "Accept": "*/*",
    "Accept-Language": "en-US,en;q=0.6",
    "Content-Type": "application/json",
    "X-Goog-AuthUser": "0",
    "x-origin": "https://music.youtube.com",
    "Cookie":"<YOUR COOKIE>"
}

Step3: You can get your cookie by visiting youtube music website -> Going to developers tools and after that click on Network tab -> Now click on Library tab in YtMusic -> In network tab a file would appear starting as browse?key=  -> Click on that file and scroll a bit, you will find your account cookie named as Cookie as a key. But make sure you were logged In.

Step4: Paste that cookie in place of YOUR COOKIE in headers_auth.json file. And run the application.
